### 验证 ES
GET {{baseUrl}}

############ 索引操作 ############
### 创建 shopping 索引
PUT {{baseUrl}}/shopping

### 查询所有索引
GET {{baseUrl}}/_cat/indices?v

### 查看单个索引
GET {{baseUrl}}/shopping

### 删除单个索引
DELETE {{baseUrl}}/shopping


############ 文档操作 ############
### 创建文档（此方式不能使用 PUT；自动生成唯一标识，可以指定，比如：xxx/shopping/_doc/1，此方式可以使用 PUT）
POST {{baseUrl}}/shopping/_doc
Content-Type: application/json

{
  "title": "小米手机",
  "category": "小米",
  "images": "http://www.gulixueyuan.com/xm.jpg",
  "price": 3999.00
}

### 新增文档（当指定唯一标识时可以使用 PUT）
PUT {{baseUrl}}/shopping/_doc/2
Content-Type: application/json

{
  "title": "华为手机",
  "category": "华为",
  "images": "http://www.gulixueyuan.com/hw.jpg",
  "price": 4999.00
}

### 查询文档（全查询）
GET {{baseUrl}}/shopping/_search

### 查询文档（主键查询）
GET {{baseUrl}}/shopping/_doc/1

### 查询文档（主键查询，查询不存在主键）
GET {{baseUrl}}/shopping/_doc/1001

### 修改文档（全量修改）
PUT {{baseUrl}}/shopping/_doc/1
Content-Type: application/json

{
  "title": "华为手机",
  "category": "华为",
  "images": "http://www.gulixueyuan.com/hw.jpg",
  "price": 4999.00
}

### 修改文档（局部修改）
POST {{baseUrl}}/shopping/_update/1
Content-Type: application/json

{
  "doc": {
    "title": "荣耀手机",
    "category": "华为",
    "price": 1999.00
  }
}

### 删除文档（逻辑删除）
DELETE {{baseUrl}}/shopping/_doc/1


############ 查询操作 ############
### 条件查询（URL带参查询）
GET {{baseUrl}}/shopping/_search?q=category:小米

### 条件查询（请求体带参查询）
GET {{baseUrl}}/shopping/_search
Content-Type: application/json

{
  "query": {
    "match": {
      "category": "华为"
    }
  }
}

### 请求体查询所有
GET {{baseUrl}}/shopping/_search
Content-Type: application/json

{
  "query": {
    "match_all": {}
  }
}

### 查询指定字段的所有内容
GET {{baseUrl}}/shopping/_search
Content-Type: application/json

{
  "query": {
    "match_all": {}
  },
  "_source": [
    "title"
  ]
}

### 分页查询（from + size 浅分页）
GET {{baseUrl}}/shopping/_search
Content-Type: application/json

{
  "query": {
    "match_all": {}
  },
  "from": 2,
  "size": 2
}

### 分页查询（scroll 深分页）
GET {{baseUrl}}/shopping/_search?scroll=5m
Content-Type: application/json

{
  "query": {
    "match_all": {}
  },
  "from": 0,
  "size": 2
}

### 分页查询（查询 scroll 下一页数据）
GET {{baseUrl}}/_search/scroll
Content-Type: application/json

{
  "scroll_id": "FGluY2x1ZGVfY29udGV4dF91dWlkDXF1ZXJ5QW5kRmV0Y2gBFnJvdmFGQ2NqUjY2TU9heHN0OVhLT3cAAAAAAAAySRZpaFhpY3BqalNoT1NNaXRmUnpVdlJB",
  "scroll": "5m"
}

### 删除指定的 scroll
DELETE {{baseUrl}}/_search/scroll/FGluY2x1ZGVfY29udGV4dF91dWlkDXF1ZXJ5QW5kRmV0Y2gBFnJvdmFGQ2NqUjY2TU9heHN0OVhLT3cAAAAAAAAySRZpaFhpY3BqalNoT1NNaXRmUnpVdlJB

### 删除所有的 scroll
DELETE {{baseUrl}}/_search/scroll/_all

### search_after 深分页
GET {{baseUrl}}/shopping/_search
Content-Type: application/json

{
  "query": {
    "match_all": {}
  },
  "from": 0,
  "size": 2,
  "sort": [
    {
      "_id": {
        "order": "desc"
      }
    }
  ]
}

### search_after 深分页，查询下一页数据
GET {{baseUrl}}/shopping/_search
Content-Type: application/json

{
  "query": {
    "match_all": {}
  },
  "from": 0,
  "size": 2,
  "search_after": [
    3
  ],
  "sort": [
    {
      "_id": {
        "order": "desc"
      }
    }
  ]
}

### 查询排序
GET {{baseUrl}}/shopping/_search
Content-Type: application/json

{
  "query": {
    "match_all": {}
  },
  "sort": {
    "price": {
      "order": "desc"
    }
  }
}

### 多条件查询（must 多条件查询）
GET {{baseUrl}}/shopping/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "category": "华为"
          }
        },
        {
          "match": {
            "price": 4999.00
          }
        }
      ]
    }
  }
}

### 多条件查询（should 多条件查询）
GET {{baseUrl}}/shopping/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "should": [
        {
          "match": {
            "category": "小米"
          }
        },
        {
          "match": {
            "category": "华为"
          }
        }
      ]
    }
  }
}

### 范围查询
GET {{baseUrl}}/shopping/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "should": [
        {
          "match": {
            "category": "小米"
          }
        },
        {
          "match": {
            "category": "华为"
          }
        }
      ],
      "filter": {
        "range": {
          "price": {
            "gt": 2000
          }
        }
      }
    }
  }
}

### 全文检索
GET {{baseUrl}}/shopping/_search
Content-Type: application/json

{
  "query": {
    "match": {
      "category": "小华"
    }
  }
}

### 全匹配
GET {{baseUrl}}/shopping/_search
Content-Type: application/json

{
  "query": {
    "match_phrase": {
      "category": "为"
    }
  }
}

### 高亮查询
GET {{baseUrl}}/shopping/_search
Content-Type: application/json

{
  "query": {
    "match_phrase": {
      "category": "为"
    }
  },
  "highlight": {
    "fields": {
      "category": {}
    }
  }
}

### 聚合查询-分组（group by）
GET {{baseUrl}}/shopping/_search
Content-Type: application/json

{
  "aggs": {
    "price_group": {
      "terms": {
        "field": "price"
      }
    }
  },
  "size": 0
}

### 聚合查询-平均值（avg）
GET {{baseUrl}}/shopping/_search
Content-Type: application/json

{
  "aggs": {
    "price_avg": {
      "avg": {
        "field": "price"
      }
    }
  },
  "size": 0
}

### 聚合查询-最大值与最小值（max,min）
GET {{baseUrl}}/shopping/_search
Content-Type: application/json

{
  "aggs": {
    "price_max": {
      "max": {
        "field": "price"
      }
    },
    "price_min": {
      "min": {
        "field": "price"
      }
    }
  },
  "size": 0
}

############ 映射操作 ############
### 创建 user 索引
PUT {{baseUrl}}/user

### 创建映射
PUT {{baseUrl}}/user/_mapping
Content-Type: application/json

{
  "properties": {
    "name": {
      "type": "text",
      "index": true
    },
    "sex": {
      "type": "keyword",
      "index": true
    },
    "tel": {
      "type": "keyword",
      "index": false
    },
    "age": {
      "type": "keyword",
      "index": true
    }
  }
}

### 查询所有映射
GET {{baseUrl}}/_mapping

### 查询指定映射
GET {{baseUrl}}/user/_mapping

### 新增映射数据
PUT {{baseUrl}}/user/_create/1001
Content-Type: application/json

{
  "name":"小明",
  "sex":"男",
  "tel":"18312345678",
  "age": 20
}

### 修改映射数据
POST {{baseUrl}}/user/_update/1001
Content-Type: application/json

{
  "doc": {
    "sex": "男的"
  }
}

### 查询指定条件映射数据（查找 name 含有 ”小“ 的信息数据）
GET {{baseUrl}}/user/_search
Content-Type: application/json

{
  "query": {
    "match": {
      "name": "小"
    }
  }
}

### 查询指定条件映射数据（查找 sex 含有 ”男“ 的信息数据）
GET {{baseUrl}}/user/_search
Content-Type: application/json

{
  "query": {
    "match": {
      "sex": "男"
    }
  }
}

### 查询指定条件映射数据（查找 sex 含有 ”男的“ 的信息数据）
GET {{baseUrl}}/user/_search
Content-Type: application/json

{
  "query": {
    "match": {
      "sex": "男的"
    }
  }
}

### 查询指定条件映射数据（查找 tel 是 “18312345678” 的信息数据）
GET {{baseUrl}}/user/_search
Content-Type: application/json

{
  "query": {
    "match": {
      "tel": "18312345678"
    }
  }
}


############ API文档操作 ############
### 查询 user 索引
GET {{baseUrl}}/user
Content-Type: application/json

### 查询 user 文档数据
GET {{baseUrl}}/user/_search
Content-Type: application/json

{
  "query": {
    "match_all": {}
  }
}
